# Informacion General del Proyecto
spring.application.name=focusmemo_api
application.version=1.0
application.descripcion=--- API REST con JPA + MariaDB para la app FocusMemo ---

# Configuracion del acceso al SGBD MariaDB y a la BD
spring.datasource.url=jdbc:mariadb://localhost:3306/focusmemo
spring.datasource.username=admin
spring.datasource.password=admin

# Permitir que los componentes se llamen entre si de forma circular
spring.main.allow-circular-references=true

# Configuracion de Persistencia y Debug de SQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuracion de mensajes de error para la API
server.error.include-message=always
server.error.include-binding-errors=always

# Forzar driver (si es necesario)
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver